name: Voting App 

on:
  push:
    branches: main
  pull_request:

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Vote Image
        run: docker build -t vote:${{ github.sha }} ./vote

      - name: Scan Vote image
        id: scan
        uses: sysdiglabs/scan-action@v6
        with:
            image-tag: vote:${{ github.sha }}
            sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

      - name: Build Worker Image
        run: docker build -t worker:${{ github.sha }} ./worker

      - name: Scan Worker image
        uses: sysdiglabs/scan-action@v6
        with:
            image-tag: worker:${{ github.sha }}
            sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

      - name: Build Result Image
        run: docker build -t result:${{ github.sha }} ./result

      - name: Scan Result image
        uses: sysdiglabs/scan-action@v6
        with:
            image-tag: result:${{ github.sha }}
            sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

      - name: Show Built Images
        run: docker images


